name: loginapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  assets:
  - assets/icons/
  - assets/icons/chat.svg
  - assets/images/

  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
  

